# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoHeaderAdSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoHeaderAdSample
  pod 'Equativ-Display-SDK', '~> 8.1'

end
